---
sudo: true

addons:
  apt:
    packages:
      - docker-ce
      - python
      - realpath
      - ruby

language: go

env:
  global:
    - GO_METALINTER_VERSION="v2.0.11"
    - GO_METALINTER_THREADS=4

go:
  # Kubernetes minimum_go_version can be found in this file:
  # https://github.com/kubernetes/kubernetes/blob/master/hack/lib/golang.sh
  - stable

install:
  - gem install asciidoctor mdl
  - pip install --user --upgrade pip
  - pip install --user yamllint
  # install dep and gometalinter
  - scripts/install-go-tools.sh

script:
  # Lint text-like files
  - scripts/pre-commit.sh --require-all
  # Fetch vendor dependencies so linters succeed
  - dep ensure -v -vendor-only
  # Lint golang sources
  - scripts/lint-go.sh
  # Build container w/ Docker
  - docker version
  - ./build.sh
